# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d3557ce5e6665bc7022e6dcf9fe771f1e555a0363907264de8db6e697b33d5947705ecb58d09459cbf1d45d8635aa4b02225c6063fae4f398da70434648e251

test:
  secret_key_base: a83339f9918d474ca8cb31a64146cdbc5d70afd7c44c2a451081aedf65945e8ef0a5459cb43c80253826e0f22576fd980030c50548f5885a384f714615509264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
